// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt9GdTP0lvbWIbRzC98fZd8Ry2Ug9Q35g',
    appId: '1:730641614937:android:7a68a8c9b0be09786f0948',
    messagingSenderId: '730641614937',
    projectId: 'traxio-app-13c13',
    storageBucket: 'traxio-app-13c13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt9GdTP0lvbWIbRzC98fZd8Ry2Ug9Q35g',
    appId: '1:730641614937:ios:7a68a8c9b0be09786f0948',
    messagingSenderId: '730641614937',
    projectId: 'traxio-app-13c13',
    storageBucket: 'traxio-app-13c13.firebasestorage.app',
    iosBundleId: 'com.example.traxio',
  );
}
